# Numpy

In [2]:
import numpy

In [3]:
vector=[1,2,3]
print(type(vector))

<class 'list'>


In [4]:
nvector=numpy.array(vector)

In [5]:
nvector.shape

(3,)

In [6]:
matrix=[[1,2,3],
       [4,5,6],
       [7,8,9]]

In [7]:
nmatrix=numpy.array(matrix)

In [8]:
nmatrix.shape

(3, 3)

In [9]:
narr=numpy.array([1,2,3])
narr

array([1, 2, 3])

In [10]:
numpy.resize(narr,(4,4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [11]:
narr.resize((3,3),refcheck=False)


In [12]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
matrix=numpy.ones((3,4))
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
matrix=numpy.zeros((3,3))
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
numpy.diag([7,8,9,5])

array([[7, 0, 0, 0],
       [0, 8, 0, 0],
       [0, 0, 9, 0],
       [0, 0, 0, 5]])

In [16]:
numpy.repeat([1,2,3],4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [17]:
m1=numpy.ones((3,3),int)
m1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
numpy.vstack([m1,matrix])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
numpy.hstack([m1,matrix])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [20]:
x=numpy.array([1,2,3])
y=numpy.array([4,5,6])

In [21]:
z=x*y
z

array([ 4, 10, 18])

In [22]:
x**2

array([1, 4, 9], dtype=int32)

In [23]:
x.dot(y)

32

In [24]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [26]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [27]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
narr.sum()

6

In [29]:
narr.max()

3

In [30]:
narr.min()

0

In [31]:
narr.argmax()

2

In [32]:
narr.argmin()

3

In [33]:
narr.mean()

0.6666666666666666

In [34]:
narr.std()

1.0540925533894598

In [35]:
mr=numpy.arange(15)**2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196], dtype=int32)

In [36]:
mr[2]

4

In [37]:
mr[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [38]:
mr[:5]

array([ 0,  1,  4,  9, 16], dtype=int32)

In [39]:
mr[-2:]

array([169, 196], dtype=int32)

In [40]:
mr[5:12:3]

array([ 25,  64, 121], dtype=int32)

In [41]:
mr[10::-2]

array([100,  64,  36,  16,   4,   0], dtype=int32)

In [42]:
mr[-10:-2:2]

array([ 25,  49,  81, 121], dtype=int32)

In [43]:
mr[2:-4:3]

array([ 4, 25, 64], dtype=int32)

In [44]:
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196], dtype=int32)

In [45]:
mr[1:12:-5]

array([], dtype=int32)

In [46]:
mr[11:-1:2]

array([121, 169], dtype=int32)

In [47]:
mr


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196], dtype=int32)

In [48]:
mr[5:19:6]

array([ 25, 121], dtype=int32)

In [49]:
mr[10:0:-2]

array([100,  64,  36,  16,   4], dtype=int32)

In [50]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
narr[0:2,1:3]

array([[2, 3],
       [0, 0]])

In [53]:
narr[::2,-1]

array([3, 0])

In [54]:
narr[::2,-1:]

array([[3],
       [0]])

In [55]:
narr[1:-1:1,2::2]

array([[0]])

In [56]:
narr[::2,-1]

array([3, 0])

In [57]:
narr[-3:-1,0::2]

array([[1, 3],
       [0, 0]])

In [58]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [59]:
narr[1:-1:2,-1:]

array([[0]])

In [60]:
narr[-1:2,-2]

array([], dtype=int32)